const CANDIDATES = [
  { id: "cand01", name: "Yesid",  costume: "Egipcio",  img: "img/candidates/cand01.png" },
  { id: "cand02", name: "Yesid",  costume: "Egipcio",    img: "img/candidates/cand01.png" },
  { id: "cand03", name: "Yesid",  costume: "Egipcio",     img: "img/candidates/cand01.png" },
  { id: "cand04", name: "Yesid",  costume: "Egipcio",    img: "img/candidates/cand01.png" },
  { id: "cand05", name: "Yesid",  costume: "Egipcio",  img: "img/candidates/cand01.png" },
  { id: "cand06", name: "Yesid",  costume: "Egipcio",    img: "img/candidates/cand01.png" },
  { id: "cand07", name: "Yesid",  costume: "Egipcio",    img: "img/candidates/cand01.png" },
  { id: "cand08", name: "Yesid",  costume: "Egipcio",    img: "img/candidates/cand01.png" },
  { id: "cand09", name: "Yesid",  costume: "Egipcio",      img: "img/candidates/cand01.png" },
  { id: "cand10", name: "Yesid",  costume: "Egipcio",   img: "img/candidates/cand01.png" },
  { id: "cand11", name: "Yesid",  costume: "Egipcio",     img: "img/candidates/cand01.png" },
  { id: "cand12", name: "Yesid",  costume: "Egipcio",     img: "img/candidates/cand01.png" },
  { id: "cand13", name: "Yesid",  costume: "Egipcio",      img: "img/candidates/cand01.png" },
  { id: "cand14", name: "Yesid",  costume: "Egipcio",    img: "img/candidates/cand01.png" },
  { id: "cand15", name: "Yesid",  costume: "Egipcio",   img: "img/candidates/cand01.png" },
  { id: "cand16", name: "Yesid",  costume: "Egipcio",   img: "img/candidates/cand01.png" },
  { id: "cand17", name: "Yesid",  costume: "Egipcio",    img: "img/candidates/cand01.png" },
  { id: "cand18", name: "Yesid",  costume: "Egipcio",   img: "img/candidates/cand01.png" },
  { id: "cand19", name: "Yesid",  costume: "Egipcio",   img: "img/candidates/cand01.png" },
  { id: "cand20", name: "Yesid",  costume: "Egipcio",    img: "img/candidates/cand01.png" },
  { id: "cand21", name: "Yesid",  costume: "Egipcio",     img: "img/candidates/cand01.png" },
  { id: "cand22", name: "Yesid",  costume: "Egipcio",    img: "img/candidates/cand01.png" },
  { id: "cand23", name: "Yesid",  costume: "Egipcio",   img: "img/candidates/cand01.png" },
  { id: "cand24", name: "Yesid",  costume: "Egipcio",    img: "img/candidates/cand01.png" },
  { id: "cand25", name: "Yesid",  costume: "Egipcio",   img: "img/candidates/cand01.png" },
  { id: "cand26", name: "Yesid",  costume: "Egipcio",  img: "img/candidates/cand01.png" },
  { id: "cand27", name: "Yesid",  costume: "Egipcio",   img: "img/candidates/cand01.png" },
  { id: "cand28", name: "Yesid",  costume: "Egipcio",   img: "img/candidates/cand01.png" },
  { id: "cand29", name: "Yesid",  costume: "Egipcio",   img: "img/candidates/cand01.png" },
  { id: "cand30", name: "Yesid",  costume: "Egipcio",   img: "img/candidates/cand01.png" },

  // Voto en blanco (sin imagen real)
  { id: "BLANCO", name: null, img: null, blank: true }
];
